export const USER_LOADING = 'USER_LOADING';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const START_LOADING_EVENTS = 'START_LOADING_EVENTS';
export const STOP_LOADING_EVENTS = 'STOP_LOADING_EVENTS';

export const START_LOADING_AUTH = 'START_LOADING_AUTH';
export const STOP_LOADING_AUTH = 'STOP_LOADING_AUTH';

export const ADD_NEW_EVENTS = 'ADD_NEW_EVENTS';
export const UPDATE_EVENT = 'UPDATE_EVENT';
export const SET_EVENTS = 'SET_EVENTS';
export const SET_HAS_FETCHED_PAST = 'SET_HAS_FETCHED_PAST"';

export const SET_BUG_REPORTS = 'SET_BUG_REPORTS';
export const ADD_BUG_REPORT = 'ADD_BUG_REPORT';
export const UPDATE_BUG_REPORT = 'UPDATE_BUG_REPORT';

export const SET_IS_LOADING = 'SET_IS_LOADING';

export const SET_SIDEBAR_OPEN = 'SET_SIDEBAR_OPEN';
export const SET_SIDEBAR_CLOSED = 'SET_SIDEBAR_CLOSED';
